config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :subscribes

  post 'manage', to: 'subscribes#manage'
  post 'sub', to: 'subscribes#sub', as: :sub
  # post 'unsub', to: 'subscribes#unsub'


  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
	validates  :email, presence: true
	validates  :sub, inclusion: ['yes', 'no']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/email_controller.rb
def new
  @email = Email.new
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController

	def manage
		if subscribe_params[:sub] == 'yes'
			redirect_to notice: "Hey thanks for signing up."
		elseif subscribe_params[:sub] =='no'
			redirect_to unsub_post
		else
			redirect_to root_path, notice: "Oops! It looks like something is missing."
		end
	end

	def sub
		@subscribe = Subscribe.find_or_initialize_by(email: subscribe_params[:email])
		if @subscribe.new_record?
			@subscribe.save!
			redirect_to root_path, notice: "Hey thanks for signing up."
		else
			redirect_to root_path, notice: "Looks like your are already here!"
		end
	end

	def unsub
		@subscribe = Subscribe.find_or_initialize_by(email: subscribe_params[:email])
		if @subscribe.new_record?
			redirect_to root_path, notice: "Looks like your are already here!"
		else
			redirect_to update_path
		end
	end



private

	def subscribe_params
		params.require(:subscribe).permit(:email, :sub)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
    @subscribe = Subscribe.new

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Email</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">

      <% if notice %>
      <%= notice %>
      <% end %>

    <%= yield %>
  </div>

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Email Caputre aka Subscribe/Unsubscibe options</h1>
<p>Ideal this will be a simple email list.  The create will be the addition of an email.
The read ...... ugh. i dunno yet.
The Update will be a link option to chancge how often your email recieves a message.
Delete will be the option of unsubscribing.
</p>


      <h5>Sign Up For Great Deals in your Email</h5>

      <%= form_for @subscribe, url: manage_path do |f|%>
          <%= f.email_field :email, placeholder: "email" %></br>
          <%= radio_button_tag(:sub, 'yes') %>
          <%= label_tag(:sub_y, "Give me Great Deals!") %>
        </br>
          <%= radio_button_tag(:sub, 'no') %>
          <%= label_tag(:sub_n, "Unsubscribe Me!") %>
        </br>
         <%= f.submit %>

      <% end %>






			<!-- <form action="#">
        <div class="form-group">
          <label for="Email">Email address</label>
          <input type="email" class="form-control" id="email" placeholder="Enter email">
        </div> -->
        <!-- <div class="form-group">
          <label for="comment">Comment:</label>
          <textarea class="form-control" rows="5" id="comment"></textarea>
        </div> -->
        <!-- <div class="form-check">
          <input type="checkbox" class="form-check-input" id="checkNews">
          <label class="form-check-label" for="checkNews">Sign Up for News and Deals!</label>
        </div>
        <button onclick="couponCode();" type="submit" class="btn">Submit</button>
      </form> -->